### ISSUE TITLE
Is there any way to validate phone number length?

### ISSUE THREAD

**Issue by amanzan** [tfcporciuncula/phonemoji#19]
For example, for Spanish numbers you shouldn't be able to enter more than 9 digits (apart from the country code); for US numbers, 10; etc

**Comment by tfcporciuncula** [comment]
You can call `PhonemojiTextInputEditText::isTextValidInternationalPhoneNumber()` and it should return false if the size is incorrect (so you can show an error state if you want, for instance). By default the formatting breaks if you go over the correct length, so that's already a good indicative the number is invalid.

There's currently no way to get the max size of a phone number based on a region since there's no API for that from libphonenumber. Even if there were, phone numbers are complicated and always changing, so I don't think it would be a good idea to use something like that to limit the number of characters users can input on the field.
