### ISSUE TITLE
Hint not supported in PhonemojiTextInputEditText

### ISSUE THREAD

**Issue by SaezChristopher** [tfcporciuncula/phonemoji#4]
If we choose to fill an `hint` in a single `PhonemojiTextInputEditText`, it seems to be ignored

**Comment by tfcporciuncula** [comment]
The `PhonemojiTextInputEditText` will never be empty (because of how the `+` will always be present there), so the `hint` will indeed never show up. We could potentially change that and treat the `+` as a [`prefixText`](https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout#setPrefixText(java.lang.CharSequence)), but since `+` is really part of the phone number, I think it makes sense it's a proper selectable part of the input there, that's the main reason behind the current implementation.

**Comment by SaezChristopher** [comment]
Can't we imagine an api / custom attr to offer the possibilty to help user to suggest via a placeholder that he could put a number (ideally formatted to the region) ?

**Comment by tfcporciuncula** [comment]
I like to think that `PhonemojiTextInputEditText`'s initial text (+XX, where XX is your current country code or whatever country you choose it to be) already tells the user they're supposed to input a phone number that includes the country code. On top of that, you can also use `PhonemojiTextInputLayout`'s `hint`, which will work normally.

I can't think of a good way of making `PhonemojiTextInputEditText`'s `hint` work, since that goes against one of the fundamental behaviors of Phonemoji which is to keep `+` always there as part of the input to ensure only international phone numbers will be properly formatted and validated.
